version: "3"
services:
  app:
    container_name: golang-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
